import { BugReport, BDDScenario } from "../types";

let outputs: any = {};
try {
  // This file is generated by AWS Amplify in production
  outputs = require('../amplify_outputs.json');
} catch (e) {
  // During local development, this file may not exist
  // The Vite dev server proxies /api to http://127.0.0.1:3005
  outputs = { custom: {} };
}

const getApiUrl = () => {
  // In production, use the Amplify API Gateway URL
  // In development, use the local proxy (handled by vite.config.ts)
  const baseUrl = outputs?.custom?.apiUrl || '';
  return baseUrl ? `${baseUrl}/api/gemini` : '/api/gemini';
};

// Helper: fetch with 30s timeout
const fetchWithTimeout = async (url: string, body: any) => {
  const controller = new AbortController();
  const id = setTimeout(() => controller.abort(), 30000);
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
      signal: controller.signal
    });
    return response;
  } finally {
    clearTimeout(id);
  }
};

export async function generateBugReport(input: string): Promise<BugReport> {
  const url = getApiUrl();
  console.log('Calling securely via proxy at:', url);

  let response;
  try {
    response = await fetchWithTimeout(url, { action: 'bug-report', input });
  } catch (err: any) {
    if (err.name === 'AbortError') throw new Error("Request to AI timed out. Please try again.");
    throw err;
  }

  if (!response.ok) {
    const errorBody = await response.text();
    if (response.status === 429) {
      throw new Error('Gemini API rate limit exceeded. Please wait a minute and try again, or upgrade your Google AI plan.');
    }
    throw new Error(`Server returned ${response.status}: ${errorBody}`);
  }

  const text = await response.text();
  if (!text) throw new Error("No response from AI server");
  return JSON.parse(text) as BugReport;
}

export async function generateBDDSteps(input: string): Promise<BDDScenario> {
  const url = getApiUrl();
  console.log('Calling securely via proxy at:', url);

  let response;
  try {
    response = await fetchWithTimeout(url, { action: 'bdd-steps', input });
  } catch (err: any) {
    if (err.name === 'AbortError') throw new Error("Request to AI timed out. Please try again.");
    throw err;
  }

  if (!response.ok) {
    const errorBody = await response.text();
    if (response.status === 429) {
      throw new Error('Gemini API rate limit exceeded. Please wait a minute and try again, or upgrade your Google AI plan.');
    }
    throw new Error(`Server returned ${response.status}: ${errorBody}`);
  }

  const text = await response.text();
  if (!text) throw new Error("No response from AI server");
  return JSON.parse(text) as BDDScenario;
}
